blog/urls.py
from os import path

from django.urls import path

from . import views
from .feeds import LatestPostsFeed


app_name = 'blog'
urlpatterns = [
    # post views
    path('', views.post_list, name='home'),
    # path('', views.PostListView.as_view(), name='home'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('user/register', views.new_user_register, name='user_register'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}
# Changing setting in the admin pannel
admin.site.site_header = "Tech Express Admin"
admin.site.site_title = "Home"
admin.site.index_title = "Admin Panel"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('', include('blog.urls', namespace='blog')),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

from django.utils.text import slugify
from django.dispatch import receiver
import os


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250, help_text='Enter news title')
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    tags = TaggableManager()

    # for adding images but need to work more for fully functional
    image = models.ImageField(
        upload_to='header_images', default=None, blank=True)
    # body = models.TextField()
    # body = RichTextField()
    body = RichTextUploadingField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
                              
    objects = models.Manager()  # The default manager.
    published = PublishedManager()  # Our custom manag

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])

    class Meta:
        ordering = ('-publish',)
    def publish_preety(self):
        return self.publish.strftime('%Y %b %e')


    def updated_preety(self):
        return self.updated.strftime('%Y %b %e')


    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    publish = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)


@receiver(models.signals.post_delete, sender=Post)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)


@receiver(models.signals.pre_save, sender=Post)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `MediaFile` object is updated
    with new file.
    """
    if not instance.pk:
        return False
    else:
        try:
            old_file = sender.objects.get(pk=instance.pk).image
        except sender.DoesNotExist:
            return None

        new_file = instance.image
        if not old_file == new_file:
            if os.path.isfile(old_file.path):
                os.remove(old_file.path)

blog/forms.py
from django import forms
from .models import Comment, Post


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea(
                                   attrs={
                'style': 'border-color: blue;',
                'placeholder': 'Write your messages here'
            }
                               ))


class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('name', 'email', 'body')


class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('title', 'slug', 'author', 'tags', 'image','body', 'status')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, TemplateView
from django.core.mail import send_mail
from django.db.models import Count
from taggit.models import Tag
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, PostForm
from django.db.models import Q
from django.http import HttpResponseRedirect
from account.views import UserRegistrationForm

# for deleting unused tag from the list of the tags


def remove_all_tags_without_objects():
    for tag in Tag.objects.all():
        if tag.taggit_taggeditem_items.count() == 0:
            tag.delete()
        else:
            pass


def post_list(request, tag_slug=None):
    remove_all_tags_without_objects()
    latest_post = Post.published.all().order_by(
        "-publish")[:5]  # This is also use less
    tag_names = Tag.objects.all().order_by('name')
    object_list = Post.published.all()

    # This code is for the search query
    query = request.GET.get("q")
    if query:
        object_list = object_list.filter(Q(title__icontains=query) |
                                         Q(body__icontains=query)
                                         )

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    # print(request.GET)
    # search = Post.objects.all()

    return render(request,
                  'blog/index.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag,
                   'tag_name': tag_names,
                   'latest_post': latest_post,  # This line is useless
                   })


def post_detail(request, year, month, day, post):    
    tag_names = Tag.objects.all().order_by('name')
    latest_post = Post.published.all().order_by(
        "-publish")[:5]  # This is also use less
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
            return HttpResponseRedirect('')
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                  .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
        .order_by('-same_tags', '-publish')[:4]

    return render(request,
                  'blog/post_detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts,
                   # This line is useless because i didn't use it for the latest post
                   'latest_post': latest_post,
                   'tag_name': tag_names})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/index.html'


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(
                cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(
                post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com',
                      [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/share.html', {'post': post,
                                               'form': form,
                                               'sent': sent})



# for register new user throug new views
def new_user_register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(
                user_form.cleaned_data['password']
            )
            new_user.save()

            return render(request,
                        'blog/register_done.html',
                        {
                            'new_user': new_user
                        })
    else:
        user_form = UserRegistrationForm()

    return render(request,
                'blog/register.html',
                {'user_form': user_form}
                )

templates/blog/about.html
{% extends 'base.html' %}  

{% block body_content %}

    
{% endblock body_content %}
    

templates/blog/contact.html
{% extends 'base.html' %}

{% block body_content %}
<div class="col-md-8">
    
    </div>
{% endblock body_content %}
    

templates/blog/index.html
{% extends 'base.html' %}
{% block title_content %}
Home
{% endblock title_content %}


{% block body_content %}
<!-- Blog Post -->
<div class="col-md-8">
	{% if tag %}
	<h2>Posts tagged with "{{ tag.name }}"</h2>
	{% endif %}
	{% for post in posts %}
	<h1 class="my-4"><a href="{{ post.get_absolute_url }}">{{ post.title|title }}</a>

		<!-- <small>
			<h3 class="small">Tags: {{ post.tags.all|join:", " }}</h3>
		</small> -->

		<small>
			<h3 class="small">
				Tags:
				{% for tag in post.tags.all %}
				<a href="{% url 'blog:post_list_by_tag' tag.slug %}">
					{{ tag.name }}
				</a>
				{% if not forloop.last %}, {% endif %}
				{% endfor %}
			</h3>
		</small>
	</h1>
	<div class="card mb-4">

		{% if post.image %}
		<img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap">
		{% else %}
		{% endif %}

		<div class="card-body">
			<p class="card-text">{{ post.body|truncatewords:60|safe }}</p>
			<a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read More &rarr;</a>
		</div>
		<div class="card-footer text-muted">
			<div class="publish_date float-left">
				<h3 class="small">Posted on {{ post.publish }} by
					<a href="https://saileshkush95.github.io/">{{ post.author }}</a></h3>
			</div>
			<div class="updated_date float-right">
				<h3 class="small">Updated on {{ post.updated }}</h3>
			</div>
		</div>

	</div>
	<div class="dropdown-divider"></div>
	{% endfor %}
	<!-- {% include "pagination.html" with page=page_obj  %} for class based views -->
	<!-- for the function based views -->
	{% include "pagination.html" with page=posts %}
</div>
{% endblock body_content %}

templates/blog/latest_posts.html
{% for post in latest_posts %}
<li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</li>
{% endfor %}

templates/blog/post_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title_content %}
{{ post.title }}
{% endblock title_content %}


{% block body_content %}
<!-- Post Content Column -->
<div class="col-lg-8">

	<!-- Title -->
	<h1 class="mt-4">{{ post.title }}</h1>
	<!-- Author -->

	<div class="publish_date float-left">
		<h3 class="small">Posted on {{ post.publish }} by
			<a href="https://saileshkush95.github.io/">{{ post.author }}</a></h3>
	</div>
	<div class="updated_date float-right">
		<h3 class="small">Updated on {{ post.updated_preety }}</h3>
	</div>
	<br>
	<hr>
	<h4 class="small">
		Share This Post
	</h4>
	<a href="{% url 'blog:post_share' post.id %}">
		<button type="button" class="btn btn-primary btn-sm"><i class="fas fa-envelope"></i></button>
	</a>
	<button type="button" class="btn btn-primary btn-sm"><i class="fab fa-facebook-f"></i></button>
	<button type="button" class="btn btn-primary btn-sm"><i class="fab fa-facebook-f"></i></button>
	<button type="button" class="btn btn-primary btn-sm"><i class="fab fa-instagram"></i></button>
	<button type="button" class="btn btn-primary btn-sm"><i class="fab fa-twitter"></i></button>
	<hr>

	<!-- Preview Image -->

	{% if post.image %}
	<img class="img-fluid rounded" src="{{ post.image.url }}" alt="">
	{% else %}
	{% endif %}


	<!-- Post Content -->
	<p class="lead">{{ post.body | safe }}</p>

	<!-- Comment Counter -->

	<div class="dropdown-divider"></div>
	{% with comments.count as total_comments %}
	<h3>
		{{ total_comments }} comment{{ total_comments|pluralize }}
	</h3>
	{% endwith %}
	<div class="dropdown-divider"></div>


	<!-- Comments Form -->
	<div class="card my-4">
		<h5 class="card-header">Leave a Comment:</h5>
		<div class="card-body">
			{% if new_comment %}
			<h2 class="small">Your comment has been added.</h2>
			<form action="." method="post">
				{% csrf_token %}
				{{ comment_form|crispy}}
				<p><input type="submit" value="Add comment"></p>
			</form>
			{% else %}
			<form action="." method="post">
				{% csrf_token %}
				{{ comment_form|crispy}}
				<button type="submit" value="Add Comment" class="btn btn-primary">Add Comment</button>
				<!-- <p><input type="submit" value="Add comment"></p> -->
			</form>
			{% endif %}
		</div>
	</div>

	{% for comment in comments %}
	<!-- Single Comment -->
	<div class="media mb-4">
		<img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
		<div class="media-body">
			<h5 class="mt-0">{{ comment.name }}</h5>
			<small>
				<p>{{ comment.publish }}</p>
			</small>
			{{ comment.body }}
		</div>
	</div>
	{% empty %}
	<p> There no comment yet.</p>
	{% endfor %}

	<!-- Comment with nested comments -->
	<!-- <div class="media mb-4">
		<img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
		<div class="media-body">
			<h5 class="mt-0">Commenter Name</h5>
			Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus
			odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate
			fringilla. Donec lacinia congue felis in faucibus.

			<div class="media mt-4">
				<img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
				<div class="media-body">
					<h5 class="mt-0">Commenter Name</h5>
					Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus
					odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate
					fringilla. Donec lacinia congue felis in faucibus.
				</div>
			</div>

			<div class="media mt-4">
				<img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
				<div class="media-body">
					<h5 class="mt-0">Commenter Name</h5>
					Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus
					odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate
					fringilla. Donec lacinia congue felis in faucibus.
				</div>
			</div>

		</div>
			
	</div> -->
</div>
<!-- /.container -->
{% endblock body_content %}

<!-- This is for the similar post -->

{% block sidebar_similar_content %}
<!-- Similar Post Widget -->
<div class="card my-4">
	<h5 class="card-header">Similar Post</h5>
	<div class="card-body">
		<div class="row">
			<div class="col">
				<ul class="list-unstyled mb-0">
					{% for post in similar_posts %}
					<li>
						<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
					</li>
					{% empty %}
					There is no similar post yet.
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
</div>

{% endblock sidebar_similar_content %}

templates/blog/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body_content %}
<div class="col-md-8">
        <div class="container">
                <div class="card card-register mx-auto mt-5">
                    <div class="card-header">Register an Account</div>
                    <div class="card-body">
                        <form action=" " method="post">
                            {% csrf_token %}
                            {{ user_form|crispy }}
                            <button class="btn btn-primary btn-block" type="submit">Register my account</button>
                        </form>
                    </div>
                </div>
            </div>
    
    </div>
{% endblock body_content %}
    

templates/blog/register_done.html
{% extends 'base.html' %}
{% block body_content %}
<div class="col-md-8">
    <p>Regestration Done</p>
</div>
{% endblock body_content %}

templates/blog/services.html
{% extends 'base.html' %}

{% block body_content %}
<div class="col-md-8">
    
</div>

    
{% endblock body_content %}
    

templates/blog/share.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Share a post{% endblock %}
{% block body_content %}
<div class="col-md-8">
{% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
        "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
{% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form action="." method="post">
        {{ form|crispy}}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary" value="Send e-mail">Share Post</button>
    </form>
{% endif %}
</div>
{% endblock %}