account/urls.py
from os import name

from django.contrib.auth import views as auth_views
from django.urls import path

from .views import view_all_post_list, dashboard, new_user_register, user_login, view_all_user, add_new_post


app_name = 'account'

urlpatterns = [
    # path('login/', user_login, name='login')
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/dashboard/', dashboard, name='dashboard'),
    path('password_change/', auth_views.PasswordChangeView.as_view(),name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('account/user', view_all_user, name='all_user'),
    path('account/new/user/', new_user_register, name='new_user_register'),
    path('dashboard/post', view_all_post_list, name='all_post_list'),
    path('dashboard/new/post', add_new_post, name='new_post'),
]

blog/urls.py
from os import path

from django.urls import path

from . import views
from .feeds import LatestPostsFeed


app_name = 'blog'
urlpatterns = [
    # post views
    path('', views.post_list, name='home'),
    # path('', views.PostListView.as_view(), name='home'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('user/register', views.new_user_register, name='user_register'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}
# Changing setting in the admin pannel
admin.site.site_header = "Tech Express Admin"
admin.site.site_title = "Home"
admin.site.index_title = "Admin Panel"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('', include('blog.urls', namespace='blog')),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

templates/account_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Tech Express Admin Login</title>

	<!-- Bootstrap core CSS-->
	<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

	<!-- Custom fonts for this template-->
	<link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

	<!-- Custom styles for this template-->
	<link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">

</head>

<body>

	{% block body_content %}

	{% endblock body_content %}


	<!-- Bootstrap core JavaScript-->
	<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

	<!-- Core plugin JavaScript-->
	<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

</body>

</html>

templates/account_base_main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Tech Express Admin | Dashboard</title>

	<!-- Bootstrap core CSS-->
	<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

	<!-- Custom fonts for this template-->
	<link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

	<!-- Custom styles for this template-->
	<link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

</head>

<body id="page-top">
	<nav class="navbar navbar-expand navbar-dark bg-dark static-top">

		<a class="navbar-brand mr-1" href="{% url 'account:dashboard' %}">Tech Express Admin</a>

		<button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
			<i class="fas fa-bars"></i>
		</button>

		<!-- Navbar Search -->
		<form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
			<div class="input-group">
				<input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
				<div class="input-group-append">
					<button class="btn btn-primary" type="button">
						<i class="fas fa-search"></i>
					</button>
				</div>
			</div>
		</form>

		<!-- Navbar -->
		<ul class="navbar-nav ml-auto ml-md-0">
			<li class="nav-item dropdown no-arrow mx-1">
				<a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
				 aria-expanded="false">
					<i class="fas fa-bell fa-fw"></i>
					<span class="badge badge-danger">9+</span>
				</a>
				<div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
					<a class="dropdown-item" href="#">Action</a>
					<a class="dropdown-item" href="#">Another action</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="#">Something else here</a>
				</div>
			</li>
			<li class="nav-item dropdown no-arrow mx-1">
				<a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown"
				 aria-haspopup="true" aria-expanded="false">
					<i class="fas fa-envelope fa-fw"></i>
					<span class="badge badge-danger">7</span>
				</a>
				<div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
					<a class="dropdown-item" href="#">Action</a>
					<a class="dropdown-item" href="#">Another action</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="#">Something else here</a>
				</div>
			</li>
			<li class="nav-item dropdown no-arrow">
				<a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
				 aria-expanded="false">
					<i class="fas fa-user-circle fa-fw"></i>
				</a>
				<div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
					<a class="dropdown-item" href="#">{{ user.username|title }}</a>
					<a class="dropdown-item" href="{% url 'account:password_change' %}">Change Password</a>
					<a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
			</li>
		</ul>

	</nav>

	<div id="wrapper">

		<!-- Sidebar -->
		<ul class="sidebar navbar-nav">
			<li class="nav-item active">
				<a class="nav-link" href="{% url 'account:dashboard' %}">
					<i class="fas fa-fw fa-tachometer-alt"></i>
					<span>Dashboard</span>
				</a>
			</li>
			<li class="nav-item ">
					<a class="nav-link" href="{% url 'blog:home' %}">
						<i class="fas fa-fw fa-tachometer-alt"></i>
						<span>Blog Home Page</span>
					</a>
				</li>
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
				 aria-expanded="false">
					<i class="fas fa-fw fa-folder"></i>
					<span>User</span>
				</a>
				<div class="dropdown-menu" aria-labelledby="pagesDropdown">
					<a class="dropdown-item" href="{% url 'account:new_user_register' %}">Add New User</a>
					<a class="dropdown-item" href="{% url 'account:all_user' %}">All Users</a>
				</div>
			</li>
			<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
					 aria-expanded="false">
						<i class="fas fa-fw fa-folder"></i>
						<span>Posts</span>
					</a>
					<div class="dropdown-menu" aria-labelledby="pagesDropdown">
						<a class="dropdown-item" href="{% url 'account:new_post' %}">Add Post</a>
						<a class="dropdown-item" href="{% url 'account:all_post_list' %}">View Post</a>
					</div>
				</li>
			<li class="nav-item">
				<a class="nav-link" href="charts.html">
					<i class="fas fa-fw fa-chart-area"></i>
					<span>Charts</span></a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="tables.html">
					<i class="fas fa-fw fa-table"></i>
					<span>Tables</span></a>
			</li>
		</ul>
		{% block body_content %}

		{% endblock body_content %}


		<!-- Bootstrap core JavaScript-->
		<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
		<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

		<!-- Core plugin JavaScript-->
		<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

		<!-- Page level plugin JavaScript-->
		<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
		<script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
		<script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>

		<!-- Custom scripts for all pages-->
		<script src="{% static 'js/sb-admin.min.js' %}"></script>

		<!-- Demo scripts for this page-->
		<script src="{% static 'js/demo/datatables-demo.js' %}"></script>
		<script src="{% static 'js/demo/chart-area-demo.js' %}"></script>

</body>

</html>

</body>

</html>

templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<link rel="shortcut icon" href="https://cdn4.iconfinder.com/data/icons/new-google-logo-2015/400/new-google-favicon-512.png"
	 type="image/x-icon">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Testinng Purpose |
		{% block title_content %}

		{% endblock title_content %}
	</title>

	<!-- Bootstrap core CSS -->
	<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

	<!-- Custom styles for this template -->
	<link href="{% static 'css/blog-home.css' %}" rel="stylesheet">

	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
	 crossorigin="anonymous">

</head>

<body>

	<!-- Navigation -->
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
		<div class="container">
			<a class="navbar-brand" href="{% url 'blog:home' %}">Tech Express</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive"
			 aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				
				{% if request.user.is_authenticated %}
				<ul class="navbar-nav ml-auto">
						<li class="nav-item">
							<a class="nav-link" href="#">{{ user.username|title }}</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'account:logout' %}">Log Out</a>
						</li>
					
					
					{% if request.user.is_superuser %}
							<li class="nav-item">
								<a class="nav-link" href="{% url 'account:dashboard' %}">Admin</a>
							</li>
					{% endif %}
				</ul>
						
				{% else %}
				<ul class="navbar-nav ml-auto">
						<li class="nav-item">
							<a class="nav-link" href="{% url 'account:login' %}">Login</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'blog:user_register' %}">Register</a>
						</li>
					</ul>
				{% endif %}
			</div>
		</div>
	</nav>
	<!-- Page Content -->
	<div class="container">

		<div class="row">

			<!-- Blog Entries Column -->



			{% block body_content %}

			{% endblock body_content %}

			<!-- Sidebar Widgets Column -->
			<div class="col-md-4">
				<!-- Search Widget -->
				<div class="card my-4">
					<h5 class="card-header">Search</h5>
					<div class="card-body">
						<form action="{% url 'blog:home' %}" method="GET">
							<input type="text" value="{{ request.GET.q }}" placeholder="Search" name="q">
							<input type="submit" class="btn btn-primary" value="search">
						</form>
						{% if message %}

						{% for k in message %}
						<li>{{ k }}</li>
						{% endfor %}
						{% endif %}

					</div>
				</div>


				{% block sidebar_similar_content %}

				{% endblock sidebar_similar_content %}

				<!-- Categories Widget -->
				<div class="card my-4">
					<h5 class="card-header">Categories</h5>
					<div class="card-body">
						<div class="row">
							<div class="col-lg-6">
								<ul class="list-unstyled mb-0">
									{% for tag in tag_name %}
									<li>
									</li>
									<a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name|capfirst }} </a>
									</li>
									{% endfor %}
								</ul>
							</div>
						</div>
					</div>
				</div>

				<!-- Side Widget -->
				<div class="card my-4">
					<h5 class="card-header">Latest News</h5>
					<div class="card-body">
						<div class="row">
							<div class="col">
								<ul class="list-unstyled mb-0">
									{% show_latest_posts 4 %}
									<!-- {% for post in latest_post %}
									<li>
										<a href="{{ post.get_absolute_url }}">{{ post.title|title }}</a>
									</li>
									{% empty %}
									There is not latest post
									{% endfor %} -->
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="card my-4">
					<h5 class="card-header">Most Commented News</h5>
					<div class="card-body">
						{% get_most_commented_posts as most_commented_posts %}
						<ul class="list-unstyled mb-0">
							{% for post in most_commented_posts %}
							<li>
								<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
							</li>
							{% endfor %}
						</ul>
					</div>
				</div>

				<div class="card my-4">
					<h5 class="card-header">Total Post</h5>
					<div class="card-body">
						<p><a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a></p>
						<h1 class="text-center">{% total_posts %}</h1>
					</div>
				</div>
				<div class="card my-4">
					<h5 class="card-header">YouTube Video</h5>
					<div class="card-body">
						You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap
						4
						card containers!
					</div>
				</div>
			</div>

		</div>
		<!-- /.row -->

	</div>
	<!-- /.container -->
	<!-- Footer -->
	<footer class="py-5 bg-dark">
		<div class="container">
			<p class="m-0 text-center text-white">Copyright &copy; Your Website 2018</p>
		</div>
		<!-- /.container -->
	</footer>

	<!-- Bootstrap core JavaScript -->
	<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

templates/pagination.html
<div class="row m-4">
    <div class="col float-left ">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}{% if request.GET.q %}& q={{ request.GET.q }}{% endif %}"><button type="submit" class="btn btn-primary float-right">Previous</button></a>
        {% endif %}
    </div>
    <div class="col float-none">
        <span class="text-center">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>

    </div>
    <div class="col float-right">
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }} {% if request.GET.q %}& q={{ request.GET.q }}{% endif %}"><button type="submit" class="btn btn-primary">Next</button></a>
        {% endif %}

    </div>
</div>